[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip nRF52833_xxAA'

[target.'cfg(not(target_os = "none"))']

[build]
target = "thumbv7em-none-eabihf"
rustflags = ["-C", "lto=thin"]

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]